# Generated by Django 6.0.4 on 2026-05-26 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dia_corte',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real brasileiro (R$)'), ('USD', 'Dólar americano (US$)'), ('EUR', 'Euro (€)'), ('GBP', 'Libra esterlina (£)')], default='BRL', max_length=3),
        ),
    ]
