# Generated by Django 5.2.16 on 2026-08-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_dia_corte_usuario_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cor_destaque',
            field=models.CharField(default='#4c8eff', max_length=7),
        ),
        migrations.AddField(
            model_name='usuario',
            name='escala_fonte',
            field=models.PositiveSmallIntegerField(choices=[(90, 'Pequena (90%)'), (100, 'Normal (100%)'), (110, 'Grande (110%)'), (125, 'Muito grande (125%)')], default=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reduzir_animacoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('escuro', 'Escuro'), ('claro', 'Claro'), ('contraste', 'Alto contraste')], default='escuro', max_length=10),
        ),
    ]
