# Generated by Django 5.2.16 on 2026-08-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_cor_destaque_usuario_escala_fonte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('escuro', 'Black'), ('midnight', 'Midnight'), ('mint', 'Mint'), ('golden', 'Golden'), ('claro', 'Snowy'), ('contraste', 'Vault')], default='escuro', max_length=10),
        ),
    ]
