# Generated by Django 5.2.16 on 2026-08-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='regra_dia_util',
            field=models.CharField(choices=[('sem_feriados', 'Segunda a sexta, sem descontar feriados'), ('com_feriados', 'Segunda a sexta, descontando feriados nacionais'), ('clt', 'Sábado conta como dia útil (exclui domingos e feriados)')], default='com_feriados', max_length=12),
        ),
    ]
