# Generated by Django 6.0.4 on 2026-05-27 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_transacaofixa'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transacaofixa',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('pessoa', 'Pessoa'), ('empresa', 'Empresa'), ('projeto', 'Projeto'), ('outro', 'Outro')], default='pessoa', max_length=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('usuario', 'nome', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='entidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financeiro.entidade'),
        ),
        migrations.AddField(
            model_name='transacaofixa',
            name='entidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_fixas', to='financeiro.entidade'),
        ),
    ]
