# Generated by Django 6.0.4 on 2026-05-28 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_transacaofixa_intervalo_dias'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tomado', 'Tomado'), ('concedido', 'Concedido')], max_length=10)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('n_parcelas', models.PositiveIntegerField()),
                ('taxa_juros', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tipo_amortizacao', models.CharField(blank=True, choices=[('price', 'Tabela Price'), ('sac', 'SAC')], default='', max_length=10)),
                ('data_inicio', models.DateField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos', to='financeiro.entidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_juros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paga', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.emprestimo')),
            ],
            options={
                'verbose_name': 'Parcela de empréstimo',
                'verbose_name_plural': 'Parcelas de empréstimo',
                'ordering': ['numero'],
            },
        ),
    ]
