# Generated by Django 6.0.4 on 2026-05-28 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_emprestimo_parcelaemprestimo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('conta', 'Conta'), ('investimento', 'Investimento'), ('cripto', 'Cripto'), ('vale', 'Vale alimentação/refeição'), ('outro', 'Outro')], default='outro', max_length=15)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_extras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saldo extra',
                'verbose_name_plural': 'Saldos extras',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
