# Generated by Django 6.0.4 on 2026-05-30 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_meta'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEssencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('icone', models.CharField(max_length=10)),
                ('prioridade', models.CharField(choices=[('fundamental', 'Fundamental'), ('importante', 'Importante'), ('opcional', 'Opcional')], default='importante', max_length=12)),
                ('variavel', models.BooleanField(default=False)),
                ('frequencia', models.CharField(default='mensal', max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('descricao', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Categoria essencial',
                'verbose_name_plural': 'Categorias essenciais',
                'ordering': ['tipo', 'prioridade', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Essencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês (1–31)', null=True)),
                ('data_inicio', models.DateField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='financeiro.categoriaessencial')),
                ('transacao_fixa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essencial', to='financeiro.transacaofixa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essenciais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Essencial',
                'verbose_name_plural': 'Essenciais',
                'ordering': ['categoria__tipo', 'categoria__prioridade', 'categoria__ordem'],
                'unique_together': {('usuario', 'categoria')},
            },
        ),
    ]
