# Generated by Django 6.0.4 on 2026-05-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_categoriaessencial_essencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essencial',
            name='freq_pagamento',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('semanal', 'Semanal')], default='mensal', max_length=10),
        ),
        migrations.AddField(
            model_name='essencial',
            name='tipo_salario',
            field=models.CharField(blank=True, choices=[('fixo', 'Salário fixo'), ('comissao', 'Comissão pura'), ('fixo_comissao', 'Fixo + Comissão')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='essencial',
            name='ultimo_registro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essencial',
            name='valor_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
