# Generated by Django 6.0.4 on 2026-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_essencial_freq_pagamento_essencial_tipo_salario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essencial',
            name='dia_util',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='essencial',
            name='dia_vencimento_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
