# Generated by Django 6.0.4 on 2026-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_essencial_dia_util_essencial_dia_vencimento_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='essencial',
            name='dia_util_2',
            field=models.BooleanField(default=False),
        ),
    ]
