# Generated by Django 6.0.4 on 2026-05-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_essencial_dia_util_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='essencial',
            name='transacao_fixa_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essencial_2', to='financeiro.transacaofixa'),
        ),
        migrations.AddField(
            model_name='essencial',
            name='valor_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
