# Generated by Django 5.2.16 on 2026-08-05 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_essencial_transacao_fixa_2_essencial_valor_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('carreira', 'Carreira'), ('educacao', 'Educação'), ('moradia', 'Moradia'), ('veiculo', 'Veículo'), ('viagem', 'Viagem'), ('saude', 'Saúde'), ('familia', 'Família'), ('financeiro', 'Conquista financeira'), ('outro', 'Outro')], default='outro', max_length=12)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, default='')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_vida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de vida',
                'verbose_name_plural': 'Eventos de vida',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
