# Generated by Django 5.2.16 on 2026-08-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_eventovida'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventovida',
            name='transacao',
            field=models.ForeignKey(blank=True, help_text='Transação financeira associada a este marco (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_vida', to='financeiro.transacao'),
        ),
    ]
