# Generated by Django 5.2.16 on 2026-08-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_eventovida_transacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='fitid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID único do lançamento no extrato importado (OFX).', max_length=120),
        ),
        migrations.CreateModel(
            name='ImportacaoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('ofx', 'OFX'), ('csv', 'CSV')], default='ofx', max_length=4)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('conta', models.CharField(blank=True, default='', max_length=60)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('n_importadas', models.PositiveIntegerField(default=0)),
                ('n_ignoradas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importação de extrato',
                'verbose_name_plural': 'Importações de extrato',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='importacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financeiro.importacaoextrato'),
        ),
        migrations.CreateModel(
            name='RegraCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(help_text='Se a descrição contiver este texto…', max_length=120)),
                ('aplica_a', models.CharField(choices=[('ambos', 'Receitas e despesas'), ('receita', 'Só receitas'), ('despesa', 'Só despesas')], default='ambos', max_length=8)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='financeiro.categoria')),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras', to='financeiro.entidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_categoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de categorização',
                'verbose_name_plural': 'Regras de categorização',
                'ordering': ['termo'],
            },
        ),
    ]
