# Generated by Django 5.2.16 on 2026-08-05 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_transacao_fitid_importacaoextrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='origem_fixa',
            field=models.ForeignKey(blank=True, help_text='Recorrente que gerou esta transação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='financeiro.transacaofixa'),
        ),
    ]
