# Generated by Django 5.2.16 on 2026-08-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_transacao_origem_fixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaofixa',
            name='dia_util_n',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Se preenchido, cai sempre no N-ésimo dia útil do mês.', null=True),
        ),
    ]
