# Generated by Django 5.2.16 on 2026-08-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_transacaofixa_dia_util_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracategoria',
            name='recorrente',
            field=models.ForeignKey(blank=True, help_text='Lançamentos casados são conciliados com esta recorrente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='financeiro.transacaofixa'),
        ),
        migrations.AlterField(
            model_name='regracategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='financeiro.categoria'),
        ),
    ]
