# Generated by Django 5.2.16 on 2026-08-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_regracategoria_recorrente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regracategoria',
            name='termo',
            field=models.CharField(help_text='Comparado com a linha inteira do extrato (operação + favorecido).', max_length=120),
        ),
    ]
