# Generated by Django 5.2.16 on 2026-08-07 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_alter_regracategoria_termo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do saldo conferido no extrato')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Saldo real da conta nessa data', max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_saldo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de saldo',
                'verbose_name_plural': 'Ajustes de saldo',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['usuario', '-data'], name='financeiro__usuario_d1a7b8_idx')],
            },
        ),
    ]
