# Generated by Django 5.2.16 on 2026-08-07 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_ajustesaldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ajustesaldo',
            name='financeiro__usuario_d1a7b8_idx',
        ),
        migrations.AddField(
            model_name='ajustesaldo',
            name='conta',
            field=models.CharField(choices=[('banco', 'Conta bancária'), ('dinheiro', 'Dinheiro'), ('vale', 'Vale alimentação/refeição'), ('outro', 'Outro')], db_index=True, default='banco', help_text='Bolso que este ajuste corrige.', max_length=10),
        ),
        migrations.AddField(
            model_name='transacao',
            name='conta',
            field=models.CharField(choices=[('banco', 'Conta bancária'), ('dinheiro', 'Dinheiro'), ('vale', 'Vale alimentação/refeição'), ('outro', 'Outro')], db_index=True, default='banco', help_text='Bolso de onde o dinheiro saiu ou entrou.', max_length=10),
        ),
        migrations.AddField(
            model_name='transacaofixa',
            name='conta',
            field=models.CharField(choices=[('banco', 'Conta bancária'), ('dinheiro', 'Dinheiro'), ('vale', 'Vale alimentação/refeição'), ('outro', 'Outro')], db_index=True, default='banco', help_text='Bolso que as ocorrências desta recorrente vão usar.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='ajustesaldo',
            index=models.Index(fields=['usuario', 'conta', '-data'], name='financeiro__usuario_f57bff_idx'),
        ),
    ]
