# Generated by Django 5.2.16 on 2026-08-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_remove_ajustesaldo_financeiro__usuario_d1a7b8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaessencial',
            name='conta',
            field=models.CharField(choices=[('banco', 'Conta bancária'), ('dinheiro', 'Dinheiro'), ('vale', 'Vale alimentação/refeição'), ('outro', 'Outro')], db_index=True, default='banco', help_text='Bolso em que este essencial movimenta dinheiro.', max_length=10),
        ),
    ]
