# Generated by Django 5.2.16 on 2026-08-07 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0022_categoriaessencial_conta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regracategoria',
            name='contrapartida_categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria da cobrança futura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras_contrapartida', to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='regracategoria',
            name='contrapartida_dia',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do vencimento da fatura (1–31). Vazio usa o dia da própria transação.', null=True),
        ),
        migrations.AddField(
            model_name='regracategoria',
            name='contrapartida_parcelas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Em quantas vezes a cobrança futura se divide.'),
        ),
        migrations.AddField(
            model_name='regracategoria',
            name='contrapartida_taxa',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Percentual somado ao valor original (ex.: 6.5 para 6,5%).', max_digits=6),
        ),
        migrations.AddField(
            model_name='regracategoria',
            name='gera_contrapartida',
            field=models.BooleanField(default=False, help_text='Lançamentos casados geram uma cobrança futura de sinal oposto.'),
        ),
        migrations.CreateModel(
            name='Contrapartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('conta', models.CharField(choices=[('banco', 'Conta bancária'), ('dinheiro', 'Dinheiro'), ('vale', 'Vale alimentação/refeição'), ('outro', 'Outro')], db_index=True, default='banco', help_text='Bolso que a cobrança vai movimentar.', max_length=10)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa', models.DecimalField(decimal_places=3, default=0, help_text='Percentual aplicado sobre o valor original.', max_digits=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrapartidas', to='financeiro.categoria')),
                ('origem', models.ForeignKey(help_text='Transação que gerou esta cobrança.', on_delete=django.db.models.deletion.CASCADE, related_name='contrapartidas', to='financeiro.transacao')),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrapartidas', to='financeiro.regracategoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrapartidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrapartida',
                'verbose_name_plural': 'Contrapartidas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaContrapartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('data_vencimento', models.DateField(db_index=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quitada', models.BooleanField(default=False)),
                ('contrapartida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contrapartida')),
                ('transacao', models.ForeignKey(blank=True, help_text='Lançamento real que quitou esta parcela.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_contrapartida', to='financeiro.transacao')),
            ],
            options={
                'verbose_name': 'Parcela de contrapartida',
                'verbose_name_plural': 'Parcelas de contrapartida',
                'ordering': ['data_vencimento', 'numero'],
            },
        ),
    ]
