# Generated by Django 5.2.16 on 2026-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0023_regracategoria_contrapartida_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'A cada mês'), ('total', 'No período inteiro')], default='mensal', help_text='Mensal reinicia a cada mês; total acumula até a data fim.', max_length=10),
        ),
    ]
