from django.urls import path

from . import views

urlpatterns = [
    path('receitas/', views.receitas, name='receitas'),
    path('receitas/nova/', views.nova_receita, name='nova_receita'),
    path('despesas/', views.despesas, name='despesas'),
    path('despesas/nova/', views.nova_despesa, name='nova_despesa'),
    path('transacao/<int:pk>/editar/', views.editar_transacao, name='editar_transacao'),
    path('transacao/<int:pk>/excluir/', views.excluir_transacao, name='excluir_transacao'),
    path('graficos/', views.graficos, name='graficos'),
    path('recorrentes/', views.fixas, name='fixas'),
    path('recorrentes/nova/', views.nova_fixa, name='nova_fixa'),
    path('recorrentes/<int:pk>/editar/', views.editar_fixa, name='editar_fixa'),
    path('recorrentes/<int:pk>/excluir/', views.excluir_fixa, name='excluir_fixa'),
    path('recorrentes/<int:pk>/toggle/', views.toggle_fixa, name='toggle_fixa'),
    path('categorias/', views.categorias, name='categorias'),
    path('categorias/nova/', views.nova_categoria, name='nova_categoria'),
    path('categorias/<int:pk>/editar/', views.editar_categoria, name='editar_categoria'),
    path('categorias/<int:pk>/excluir/', views.excluir_categoria, name='excluir_categoria'),
    path('entidades/', views.entidades, name='entidades'),
    path('entidades/nova/', views.nova_entidade, name='nova_entidade'),
    path('entidades/<int:pk>/editar/', views.editar_entidade, name='editar_entidade'),
    path('entidades/<int:pk>/excluir/', views.excluir_entidade, name='excluir_entidade'),
    path('exportar/', views.exportar_dados, name='exportar_dados'),
    path('emprestimos/', views.emprestimos, name='emprestimos'),
    path('emprestimos/novo/', views.novo_emprestimo, name='novo_emprestimo'),
    path('emprestimos/<int:pk>/editar/', views.editar_emprestimo, name='editar_emprestimo'),
    path('emprestimos/<int:pk>/excluir/', views.excluir_emprestimo, name='excluir_emprestimo'),
    path('emprestimos/parcela/<int:pk>/toggle/', views.toggle_parcela, name='toggle_parcela'),
    path('essenciais/', views.essenciais, name='essenciais'),
    path('essenciais/<slug:slug>/ativar/', views.ativar_essencial, name='ativar_essencial'),
    path('essenciais/<slug:slug>/editar/', views.editar_essencial, name='editar_essencial'),
    path('essenciais/<slug:slug>/desativar/', views.desativar_essencial, name='desativar_essencial'),
    path('metas/', views.metas, name='metas'),
    path('metas/nova/', views.nova_meta, name='nova_meta'),
    path('metas/<int:pk>/editar/', views.editar_meta, name='editar_meta'),
    path('metas/<int:pk>/excluir/', views.excluir_meta, name='excluir_meta'),
    path('metas/<int:pk>/toggle/', views.toggle_meta, name='toggle_meta'),
    path('metas/<int:pk>/ajustar/', views.ajustar_meta, name='ajustar_meta'),
    path('saldo-extra/novo/', views.criar_saldo_extra, name='criar_saldo_extra'),
    path('saldo-extra/<int:pk>/atualizar/', views.atualizar_saldo_extra, name='atualizar_saldo_extra'),
    path('saldo-extra/<int:pk>/excluir/', views.excluir_saldo_extra, name='excluir_saldo_extra'),
]
